import type { ListingScanRule } from "@/lib/scanner/types";

/** Default rules used when the database is unavailable or empty. */
export const DEFAULT_LISTING_SCAN_RULES: ListingScanRule[] = [
  {
    id: "rule-cure-claim",
    shop_id: null,
    name: "Medical cure claim",
    severity: "high",
    condition_type: "restricted_claim",
    condition_value: {
      pattern: "\\b(cure|cures|heal|heals)\\b",
      flags: "i",
      rewrite_from: "\\b(cure|cures|heal|heals)\\b",
      rewrite_to: "support",
    },
    remediation_tip:
      'Remove medical cure language. Use phrasing like "supports" or "helps maintain" instead.',
    active: true,
    blocks_publish: true,
  },
  {
    id: "rule-fda-claim",
    shop_id: null,
    name: "Unverified FDA claim",
    severity: "high",
    condition_type: "restricted_claim",
    condition_value: {
      pattern: "\\b(fda approved|fda-approved)\\b",
      flags: "i",
      rewrite_from: "\\b(FDA approved|FDA-approved)\\b",
      rewrite_to: "formulated for daily use",
    },
    remediation_tip:
      "Do not reference FDA approval unless you have documented proof on file.",
    active: true,
    blocks_publish: true,
  },
  {
    id: "rule-guarantee",
    shop_id: null,
    name: "Absolute guarantee language",
    severity: "medium",
    condition_type: "combined_regex",
    condition_value: {
      pattern: "\\b(100%|guaranteed|guarantee)\\b",
      flags: "i",
      rewrite_from: "\\b(guaranteed|100%)\\b",
      rewrite_to: "designed to",
    },
    remediation_tip:
      'Replace absolute guarantees with qualified statements such as "designed to".',
    active: true,
    blocks_publish: false,
  },
  {
    id: "rule-superlative",
    shop_id: null,
    name: "Unsubstantiated superlative",
    severity: "medium",
    condition_type: "title_regex",
    condition_value: {
      pattern: "\\b(#1|best|top rated)\\b",
      flags: "i",
      rewrite_from: "\\b(#1|best|top rated)\\b",
      rewrite_to: "",
    },
    remediation_tip:
      "Remove superlatives unless substantiated with verifiable proof.",
    active: true,
    blocks_publish: false,
  },
  {
    id: "rule-health-outcome",
    shop_id: null,
    name: "Restricted health outcome claim",
    severity: "high",
    condition_type: "restricted_claim",
    condition_value: {
      pattern: "\\b(weight loss|lose weight|fat burn)\\b",
      flags: "i",
    },
    remediation_tip:
      "Health outcome claims are restricted. Focus on product features instead.",
    active: true,
    blocks_publish: true,
  },
  {
    id: "rule-title-short",
    shop_id: null,
    name: "Title too short",
    severity: "low",
    condition_type: "title_min_length",
    condition_value: { min: 10 },
    remediation_tip:
      "Expand the title with product type, size, and key attributes.",
    active: true,
    blocks_publish: false,
  },
  {
    id: "rule-desc-short",
    shop_id: null,
    name: "Description lacks detail",
    severity: "medium",
    condition_type: "description_min_length",
    condition_value: { min: 50 },
    remediation_tip:
      "Add materials, usage instructions, and compliance-friendly details.",
    active: true,
    blocks_publish: false,
  },
  {
    id: "rule-price-invalid",
    shop_id: null,
    name: "Invalid price",
    severity: "high",
    condition_type: "price_invalid",
    condition_value: { min: 0.01 },
    remediation_tip: "Set a valid price greater than zero before publishing.",
    active: true,
    blocks_publish: true,
  },
  {
    id: "rule-price-high",
    shop_id: null,
    name: "High price point",
    severity: "low",
    condition_type: "price_above_max",
    condition_value: { max: 500 },
    remediation_tip:
      "High-ticket items may require additional seller verification.",
    active: true,
    blocks_publish: false,
  },
  {
    id: "rule-cat-beauty",
    shop_id: null,
    name: "Beauty keywords in non-beauty category",
    severity: "medium",
    condition_type: "category_mismatch",
    condition_value: {
      keywords: ["serum", "moisturizer", "skincare", "vitamin c", "spf"],
      disallowed_categories: ["electronics", "home", "fashion"],
    },
    remediation_tip:
      "Move this listing to Beauty & Personal Care or remove beauty-specific terms.",
    active: true,
    blocks_publish: false,
  },
  {
    id: "rule-cat-electronics",
    shop_id: null,
    name: "Electronics keywords in non-electronics category",
    severity: "medium",
    condition_type: "category_mismatch",
    condition_value: {
      keywords: ["bluetooth", "earbuds", "charger", "watt", "usb-c"],
      disallowed_categories: ["beauty", "food", "health"],
    },
    remediation_tip:
      "Move this listing to Electronics or remove tech-specific terms.",
    active: true,
    blocks_publish: false,
  },
  {
    id: "rule-img-before-after",
    shop_id: null,
    name: "Before/after image filename",
    severity: "high",
    condition_type: "image_filename_regex",
    condition_value: { pattern: "before.?after|results", flags: "i" },
    remediation_tip:
      "Avoid before/after imagery in beauty and health categories.",
    active: true,
    blocks_publish: false,
  },
  {
    id: "rule-img-overlay",
    shop_id: null,
    name: "Image text overlay filename",
    severity: "medium",
    condition_type: "image_filename_regex",
    condition_value: { pattern: "text|overlay|banner", flags: "i" },
    remediation_tip: "Use clean product photos without heavy text overlays.",
    active: true,
    blocks_publish: false,
  },
  {
    id: "rule-img-missing",
    shop_id: null,
    name: "Missing product images",
    severity: "high",
    condition_type: "image_count_below_min",
    condition_value: { min: 1 },
    remediation_tip: "Upload at least one clear product image before publishing.",
    active: true,
    blocks_publish: true,
  },
];
