export default function PrivacyPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16">
      <a
        href="/"
        className="mb-8 inline-block text-sm text-gray-500 hover:text-gray-700"
      >
        ← Back to home
      </a>
      <h1 className="mb-2 text-3xl font-bold">Privacy Policy</h1>
      <p className="mb-1 text-sm text-gray-500">Last updated: July 13, 2026</p>
      <p className="mb-12 text-sm text-gray-500">Effective date: July 13, 2026</p>

      <p className="mb-6 leading-relaxed">
        TikTok Shop Guard ("Service," "we," "us," or "our") is operated by
        Metamorphosis LLC, a Florida limited liability company. This Privacy
        Policy describes how we collect, use, disclose, and safeguard your
        information when you use our web application at tiktokshopguard.com. By
        accessing or using the Service, you agree to the practices described in
        this Policy. If you do not agree, please do not use the Service.
      </p>

      <div className="mb-10 rounded border-l-4 border-gray-300 bg-gray-50 px-5 py-4 text-sm leading-relaxed text-gray-700">
        <strong>Important notice:</strong> TikTok Shop Guard accesses data from
        your TikTok Shop account on your behalf using OAuth authorization. We
        treat your shop data, listing content, and account credentials with
        strict confidentiality. We do not sell this data, share it with
        advertisers, or use it for any purpose other than providing the Service
        you requested.
      </div>

      <Section title="1. Information We Collect">
        <h3 className="mt-4 font-semibold">1.1 Information You Provide Directly</h3>
        <p>
          <strong>Account registration:</strong> When you create an account, we
          collect your full name, email address, and a password. Passwords are
          hashed using industry-standard bcrypt encryption before storage. We
          never store plaintext passwords and cannot retrieve them.
        </p>
        <p>
          <strong>Profile information:</strong> You may optionally provide your
          business name, shop name, and contact preferences used to personalize
          your dashboard and communications.
        </p>
        <p>
          <strong>Support communications:</strong> If you contact us for support,
          we retain records of that correspondence, including any information you
          provide about your shop or account situation.
        </p>

        <h3 className="mt-4 font-semibold">1.2 Information From TikTok</h3>
        <p>
          <strong>OAuth authorization tokens:</strong> When you connect your
          TikTok Shop, TikTok issues us an access token and refresh token. These
          tokens are encrypted and stored server-side. They are used exclusively
          to fetch data from TikTok on your behalf and are never exposed to your
          browser or shared with any third party.
        </p>
        <p>
          <strong>Shop identity data:</strong> We receive and store your TikTok
          Shop ID, seller ID, shop name, and shop region from TikTok's API at
          the time of connection.
        </p>
        <p>
          <strong>Product listing data:</strong> To perform compliance scans, we
          retrieve your product titles, descriptions, image URLs, categories, and
          associated metadata from TikTok's product API. This data is used
          exclusively for scanning and is not shared or sold.
        </p>
        <p>
          <strong>Violation notices:</strong> If you provide violation notices
          you have received from TikTok, we store those to help generate
          appropriate appeal content.
        </p>

        <h3 className="mt-4 font-semibold">1.3 Information Generated By Our Service</h3>
        <p>
          <strong>Scan results:</strong> When you run a compliance scan, we
          generate and store the results including which listings were scanned,
          which policy rules were checked, and any potential violations
          identified. Results are tied to your account and visible only to you.
        </p>
        <p>
          <strong>Appeal drafts:</strong> When you use the AI Appeal Drafter, we
          store the input you provided and the AI-generated draft. You retain
          full control over whether to send any appeal.
        </p>
        <p>
          <strong>Appeal outcomes:</strong> If you record the outcome of an
          appeal, we store that information to help improve our violation
          detection patterns in aggregated, anonymized form only.
        </p>

        <h3 className="mt-4 font-semibold">1.4 Automatically Collected Information</h3>
        <p>
          <strong>Log data:</strong> Our servers automatically record your IP
          address, browser type and version, operating system, referring URL,
          pages visited, and time spent on pages.
        </p>
        <p>
          <strong>Cookies and session data:</strong> We use essential cookies to
          maintain your login session. We do not use advertising or tracking
          cookies. You may disable cookies in your browser settings, but doing so
          will prevent you from using the Service.
        </p>
        <p>
          <strong>Usage analytics:</strong> We collect anonymized data about how
          features are used to improve the Service. This data cannot be linked
          back to individual users.
        </p>

        <h3 className="mt-4 font-semibold">1.5 Payment Information</h3>
        <p>
          Subscription payments are processed entirely by Stripe, a PCI DSS
          Level 1 certified payment processor. We never receive, see, or store
          your credit card number, CVV, or bank account details. We receive only
          a payment confirmation, your Stripe customer ID, and your subscription
          status. For questions about payment data, see Stripe's privacy policy
          at stripe.com/privacy.
        </p>
      </Section>

      <Section title="2. How We Use Your Information">
        <p>We use the information we collect for the following purposes:</p>
        <ul className="ml-6 mt-2 list-disc space-y-2">
          <li>
            <strong>Providing the Service:</strong> To create and manage your
            account, connect to your TikTok Shop, perform compliance scans,
            generate violation alerts, and produce AI-assisted appeal drafts.
          </li>
          <li>
            <strong>Authentication and security:</strong> To verify your
            identity, maintain session security, and detect and prevent
            fraudulent or unauthorized use.
          </li>
          <li>
            <strong>Payment processing:</strong> To manage your subscription,
            process renewals, handle failed payments, and issue refunds where
            applicable.
          </li>
          <li>
            <strong>Customer support:</strong> To respond to your questions and
            resolve issues.
          </li>
          <li>
            <strong>Service improvement:</strong> To analyze aggregated,
            anonymized usage patterns to identify bugs and improve features.
          </li>
          <li>
            <strong>Legal compliance:</strong> To comply with applicable laws and
            respond to lawful requests from authorities.
          </li>
          <li>
            <strong>Communications:</strong> To send transactional emails and,
            with your consent, product updates. You may unsubscribe from
            non-transactional emails at any time.
          </li>
        </ul>
        <p className="mt-4">
          <strong>We do not:</strong> sell your personal information, use your
          listing content for advertising, share your shop data with TikTok
          competitors, or use your data to train AI models.
        </p>
      </Section>

      <Section title="3. AI Processing and Anthropic">
        <p>
          TikTok Shop Guard uses Claude, an AI model operated by Anthropic, PBC,
          to power the Appeal Drafter feature. When you request an appeal draft,
          we transmit the following to Anthropic's API:
        </p>
        <ul className="ml-6 mt-2 list-disc space-y-2">
          <li>The product listing title and description you selected</li>
          <li>The violation type and policy category identified</li>
          <li>Any additional context you choose to provide in the appeal form</li>
        </ul>
        <p className="mt-4">
          This data is transmitted over an encrypted connection. Anthropic
          processes it solely to generate the appeal response. We do not send
          personally identifiable information such as your name, email, or TikTok
          credentials to Anthropic. Per Anthropic's API terms, content submitted
          via the API is not used to train their models. See anthropic.com/privacy
          for more information.
        </p>
        <p>
          AI-generated appeal drafts are suggestions only. You remain responsible
          for reviewing, editing, and approving any content before submitting it
          to TikTok.
        </p>
      </Section>

      <Section title="4. Information Sharing and Disclosure">
        <p>
          We do not sell, rent, or trade your personal information. We share
          information only in the following limited circumstances:
        </p>

        <h3 className="mt-4 font-semibold">4.1 Service Providers</h3>
        <ul className="ml-6 mt-2 list-disc space-y-2">
          <li>
            <strong>Supabase (Supabase, Inc.):</strong> Database, authentication,
            and backend infrastructure. Your data is stored with row-level
            security enforced. Hosted in the United States.
          </li>
          <li>
            <strong>TikTok Open Platform (ByteDance Ltd.):</strong> We make API
            calls to TikTok on your behalf using your OAuth tokens to retrieve
            shop and listing data for scanning.
          </li>
          <li>
            <strong>Anthropic, PBC:</strong> AI processing for the Appeal Drafter
            feature. See Section 3.
          </li>
          <li>
            <strong>Stripe, Inc.:</strong> Subscription billing and payment
            processing. PCI DSS Level 1 certified.
          </li>
          <li>
            <strong>Vercel, Inc.:</strong> Web hosting and deployment
            infrastructure.
          </li>
        </ul>

        <h3 className="mt-4 font-semibold">4.2 Legal Requirements</h3>
        <p>
          We may disclose your information if required by law, to protect the
          rights or safety of Metamorphosis LLC or our users, or to investigate
          violations of our Terms of Service.
        </p>

        <h3 className="mt-4 font-semibold">4.3 Business Transfers</h3>
        <p>
          If Metamorphosis LLC is involved in a merger, acquisition, or sale of
          assets, your information may be transferred. We will notify you before
          your information becomes subject to a different privacy policy.
        </p>
      </Section>

      <Section title="5. Data Retention">
        <ul className="ml-6 mt-2 list-disc space-y-2">
          <li>
            <strong>Account and profile data:</strong> Retained while your
            account is active and for 90 days after deletion.
          </li>
          <li>
            <strong>Scan results and violation history:</strong> Retained while
            your account is active. You may delete individual scans at any time.
          </li>
          <li>
            <strong>Appeal drafts:</strong> Retained until you delete them or
            close your account.
          </li>
          <li>
            <strong>OAuth tokens:</strong> Immediately invalidated and deleted
            when you disconnect your shop, revoke access through TikTok, or
            delete your account.
          </li>
          <li>
            <strong>Payment records:</strong> Retained for 7 years to comply with
            financial record-keeping requirements.
          </li>
          <li>
            <strong>Server logs:</strong> Retained for 90 days for security
            monitoring, then automatically deleted.
          </li>
        </ul>
        <p className="mt-4">
          To request full account deletion, email support@tiktokshopguard.com
          with the subject "Account Deletion Request." We will process your
          request within 30 days and confirm when deletion is complete.
        </p>
      </Section>

      <Section title="6. Data Security">
        <ul className="ml-6 mt-2 list-disc space-y-2">
          <li>
            <strong>Encryption in transit:</strong> All data is encrypted using
            TLS 1.2 or higher between your browser and our servers.
          </li>
          <li>
            <strong>Encryption at rest:</strong> OAuth tokens and sensitive
            credentials are encrypted using AES-256 before storage.
          </li>
          <li>
            <strong>Password security:</strong> Passwords are hashed using bcrypt
            with a minimum cost factor of 12.
          </li>
          <li>
            <strong>Row-level security:</strong> Our database enforces policies
            that ensure your data is accessible only to your account.
          </li>
          <li>
            <strong>Token isolation:</strong> TikTok OAuth tokens are stored
            exclusively server-side and never transmitted to the client browser.
          </li>
          <li>
            <strong>Access controls:</strong> Internal access to production data
            requires multi-factor authentication and is restricted to essential
            personnel.
          </li>
        </ul>
        <p className="mt-4">
          No method of transmission or storage is 100% secure. If you believe
          your account has been compromised, contact us immediately at
          support@tiktokshopguard.com.
        </p>
      </Section>

      <Section title="7. Your Rights and Choices">
        <h3 className="mt-4 font-semibold">7.1 Access and Portability</h3>
        <p>
          You may request a copy of the personal information we hold about you by
          contacting support@tiktokshopguard.com. We will provide it in a
          machine-readable format within 30 days.
        </p>

        <h3 className="mt-4 font-semibold">7.2 Correction</h3>
        <p>
          You may update your name, email, and profile information at any time
          through your account settings.
        </p>

        <h3 className="mt-4 font-semibold">7.3 Deletion</h3>
        <p>
          You may delete individual scans and appeal drafts from your dashboard.
          To delete your entire account, email support@tiktokshopguard.com.
        </p>

        <h3 className="mt-4 font-semibold">7.4 TikTok Connection</h3>
        <p>
          You may disconnect your TikTok Shop at any time from your account
          settings, which immediately revokes our access and deletes all stored
          OAuth tokens. You may also revoke access directly through TikTok under
          Connected Apps.
        </p>

        <h3 className="mt-4 font-semibold">7.5 California Residents (CCPA/CPRA)</h3>
        <p>
          California residents have the right to know what personal information
          we collect and how we use it, request deletion, opt out of the sale or
          sharing of personal information (we do not sell or share your data),
          and not be discriminated against for exercising these rights. Contact
          support@tiktokshopguard.com to exercise these rights. We will respond
          within 45 days.
        </p>

        <h3 className="mt-4 font-semibold">7.6 EEA, UK, and Switzerland (GDPR)</h3>
        <p>
          If you are located in the EEA, UK, or Switzerland, you have rights
          under applicable data protection law including the right to object to
          processing, restrict processing, and lodge a complaint with your
          supervisory authority. Our legal bases for processing are your consent,
          contract performance, legal obligation, and legitimate interests.
          Contact us to exercise these rights.
        </p>
      </Section>

      <Section title="8. Cookies">
        <p>
          We use essential cookies for authentication and session management. The
          Service cannot function without these. We do not use advertising
          cookies, tracking pixels, or third-party analytics that track you
          across websites.
        </p>
      </Section>

      <Section title="9. Children's Privacy">
        <p>
          TikTok Shop Guard is intended for adults aged 18 and older. We do not
          knowingly collect personal information from anyone under 18. If we
          learn that we have collected information from a minor, we will delete it
          promptly. Contact support@tiktokshopguard.com if you believe a minor
          has provided us with personal information.
        </p>
      </Section>

      <Section title="10. Data Transfers">
        <p>
          Metamorphosis LLC is based in the United States. If you access the
          Service from outside the United States, your information may be
          transferred to and processed in the United States. By using the
          Service, you consent to this transfer. We take reasonable steps to
          ensure your data is handled securely regardless of where it is
          processed.
        </p>
      </Section>

      <Section title="11. Changes to This Policy">
        <p>
          When we make material changes to this policy, we will post the updated
          version here with a new effective date, send an email notification to
          your registered address, and display a notice within the Service for 30
          days. Your continued use of the Service after the effective date
          constitutes acceptance of the revised policy.
        </p>
      </Section>

      <Section title="12. Contact">
        <p>
          If you have questions, concerns, or requests regarding this Privacy
          Policy, please contact us:
        </p>
        <div className="mt-4 rounded-lg bg-gray-50 px-5 py-4 text-sm">
          <p className="font-semibold">TikTok Shop Guard</p>
          <p>Operated by Metamorphosis LLC</p>
          <p>
            Email:{" "}
            <a
              href="mailto:support@tiktokshopguard.com"
              className="text-gray-700 underline"
            >
              support@tiktokshopguard.com
            </a>
          </p>
          <p>State of Florida, United States</p>
        </div>
        <p className="mt-4">
          We will respond to all privacy-related inquiries within 30 days. For
          urgent security concerns, include "URGENT" in the subject line.
        </p>
      </Section>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mb-10">
      <h2 className="mb-4 border-b border-gray-200 pb-2 text-xl font-semibold">
        {title}
      </h2>
      <div className="flex flex-col gap-3 leading-relaxed text-gray-700">
        {children}
      </div>
    </section>
  );
}
